// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SatelliteSite;

#nullable disable

namespace SatelliteSite.Migrations
{
    partial class DependencyUpgrade
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Ccs.Entities.Balloon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Done")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasAlternateKey("SubmissionId");

                    b.ToTable("ContestBalloons", (string)null);
                });

            modelBuilder.Entity("Ccs.Entities.Clarification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Answered")
                        .HasColumnType("bit");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("ContestId")
                        .HasColumnType("int");

                    b.Property<string>("JuryMember")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProblemId")
                        .HasColumnType("int");

                    b.Property<int?>("Recipient")
                        .HasColumnType("int");

                    b.Property<int?>("ResponseToId")
                        .HasColumnType("int");

                    b.Property<int?>("Sender")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SubmitTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId");

                    b.HasIndex("ResponseToId");

                    b.HasIndex("ContestId", "Recipient");

                    b.HasIndex("ContestId", "Sender");

                    b.ToTable("ContestClarifications", (string)null);
                });

            modelBuilder.Entity("Ccs.Entities.Contest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<double?>("EndTimeSeconds")
                        .HasColumnType("float")
                        .HasColumnName("EndTime");

                    b.Property<double?>("FreezeTimeSeconds")
                        .HasColumnType("float")
                        .HasColumnName("FreezeTime");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProblemCount")
                        .HasColumnType("int");

                    b.Property<int>("RankingStrategy")
                        .HasColumnType("int");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TeamCount")
                        .HasColumnType("int");

                    b.Property<double?>("UnfreezeTimeSeconds")
                        .HasColumnType("float")
                        .HasColumnName("UnfreezeTime");

                    b.HasKey("Id");

                    b.ToTable("Contests", (string)null);
                });

            modelBuilder.Entity("Ccs.Entities.ContestProblem", b =>
                {
                    b.Property<int>("ContestId")
                        .HasColumnType("int");

                    b.Property<int>("ProblemId")
                        .HasColumnType("int");

                    b.Property<bool>("AllowSubmit")
                        .HasColumnType("bit");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.HasKey("ContestId", "ProblemId");

                    b.HasIndex("ProblemId");

                    b.HasIndex("ContestId", "ShortName")
                        .IsUnique();

                    b.ToTable("ContestProblems", (string)null);
                });

            modelBuilder.Entity("Ccs.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContestId")
                        .HasColumnType("int");

                    b.Property<string>("EndpointId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("EndpointType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset>("EventTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.HasIndex("EventTime");

                    b.ToTable("ContestEvents", (string)null);
                });

            modelBuilder.Entity("Ccs.Entities.Jury", b =>
                {
                    b.Property<int>("ContestId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.HasKey("ContestId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ContestJury", (string)null);
                });

            modelBuilder.Entity("Ccs.Entities.Member", b =>
                {
                    b.Property<int>("ContestId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LastLoginIp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Temporary")
                        .HasColumnType("bit");

                    b.HasKey("ContestId", "TeamId", "UserId");

                    b.HasIndex("UserId");

                    b.HasIndex("ContestId", "UserId")
                        .IsUnique();

                    b.ToTable("ContestMembers", (string)null);
                });

            modelBuilder.Entity("Ccs.Entities.Printing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ContestId")
                        .HasColumnType("int");

                    b.Property<bool?>("Done")
                        .HasColumnType("bit");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("LanguageId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<byte[]>("SourceCode")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.HasIndex("UserId");

                    b.ToTable("ContestPrintings", (string)null);
                });

            modelBuilder.Entity("Ccs.Entities.RankCache", b =>
                {
                    b.Property<int>("ContestId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("LastAcPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("LastAcRestricted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("PointsPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("PointsRestricted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalTimePublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalTimeRestricted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ContestId", "TeamId");

                    b.ToTable("ContestRankCache", (string)null);
                });

            modelBuilder.Entity("Ccs.Entities.ScoreCache", b =>
                {
                    b.Property<int>("ContestId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("ProblemId")
                        .HasColumnType("int");

                    b.Property<bool>("FirstToSolve")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsCorrectPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsCorrectRestricted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("PendingPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("PendingRestricted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("ScorePublic")
                        .HasColumnType("int");

                    b.Property<int?>("ScoreRestricted")
                        .HasColumnType("int");

                    b.Property<double?>("SolveTimePublic")
                        .HasColumnType("float");

                    b.Property<double?>("SolveTimeRestricted")
                        .HasColumnType("float");

                    b.Property<int>("SubmissionPublic")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SubmissionRestricted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ContestId", "TeamId", "ProblemId");

                    b.ToTable("ContestScoreCache", (string)null);
                });

            modelBuilder.Entity("Ccs.Entities.Team", b =>
                {
                    b.Property<int>("ContestId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("AffiliationId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ContestTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Location")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset?>("RegisterTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("ContestId", "TeamId");

                    b.HasIndex("AffiliationId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ContestId", "Status");

                    b.ToTable("ContestTeams", (string)null);
                });

            modelBuilder.Entity("Ccs.Entities.Visibility", b =>
                {
                    b.Property<int>("ContestId")
                        .HasColumnType("int");

                    b.Property<int>("AffiliationId")
                        .HasColumnType("int");

                    b.HasKey("ContestId", "AffiliationId");

                    b.HasIndex("AffiliationId");

                    b.ToTable("ContestTenants", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Polygon.Entities.Executable", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("ExecId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Md5sum")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ZipFile")
                        .IsRequired()
                        .HasMaxLength(1048576)
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("ZipSize")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PolygonExecutables", (string)null);
                });

            modelBuilder.Entity("Polygon.Entities.InternalError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ErrorId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ContestId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Disabled")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JudgehostLog")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JudgingId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("PolygonErrors", (string)null);
                });

            modelBuilder.Entity("Polygon.Entities.Judgehost", b =>
                {
                    b.Property<string>("ServerName")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("PollTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ServerName");

                    b.ToTable("PolygonJudgehosts", (string)null);
                });

            modelBuilder.Entity("Polygon.Entities.Judging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("JudgingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("CompileError")
                        .HasMaxLength(131072)
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int?>("ExecuteMemory")
                        .HasColumnType("int");

                    b.Property<int?>("ExecuteTime")
                        .HasColumnType("int");

                    b.Property<bool>("FullTest")
                        .HasColumnType("bit");

                    b.Property<int>("PolygonVersion")
                        .HasColumnType("int");

                    b.Property<int?>("PreviousJudgingId")
                        .HasColumnType("int");

                    b.Property<int?>("RejudgingId")
                        .HasColumnType("int");

                    b.Property<string>("RunVerdicts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Server")
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTimeOffset?>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("StopTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("int");

                    b.Property<int?>("TotalScore")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PreviousJudgingId");

                    b.HasIndex("RejudgingId");

                    b.HasIndex("Server");

                    b.HasIndex("Status");

                    b.HasIndex("SubmissionId");

                    b.ToTable("PolygonJudgings", (string)null);
                });

            modelBuilder.Entity("Polygon.Entities.JudgingRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RunId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTimeOffset>("CompleteTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("ExecuteMemory")
                        .HasColumnType("int");

                    b.Property<int>("ExecuteTime")
                        .HasColumnType("int");

                    b.Property<int>("JudgingId")
                        .HasColumnType("int");

                    b.Property<string>("MetaData")
                        .IsRequired()
                        .HasMaxLength(131072)
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("OutputDiff")
                        .IsRequired()
                        .HasMaxLength(131072)
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<string>("OutputSystem")
                        .IsRequired()
                        .HasMaxLength(131072)
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TestcaseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JudgingId");

                    b.HasIndex("TestcaseId");

                    b.ToTable("PolygonJudgingRuns", (string)null);
                });

            modelBuilder.Entity("Polygon.Entities.Language", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("LangId");

                    b.Property<bool>("AllowJudge")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowSubmit")
                        .HasColumnType("bit");

                    b.Property<string>("CompileScript")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<double>("TimeFactor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CompileScript");

                    b.ToTable("PolygonLanguages", (string)null);
                });

            modelBuilder.Entity("Polygon.Entities.Problem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProblemId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("AllowJudge")
                        .HasColumnType("bit");

                    b.Property<bool>("AllowSubmit")
                        .HasColumnType("bit");

                    b.Property<bool>("CombinedRunCompare")
                        .HasColumnType("bit");

                    b.Property<string>("CompareArguments")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("CompareScript")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<int>("MemoryLimit")
                        .HasColumnType("int");

                    b.Property<int>("OutputLimit")
                        .HasColumnType("int");

                    b.Property<string>("RunScript")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.Property<bool>("Shared")
                        .HasColumnType("bit");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("TimeLimit")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("CompareScript");

                    b.HasIndex("RunScript");

                    b.ToTable("PolygonProblems", (string)null);
                });

            modelBuilder.Entity("Polygon.Entities.ProblemAuthor", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ProblemId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.HasKey("UserId", "ProblemId");

                    b.HasIndex("ProblemId");

                    b.HasIndex("UserId");

                    b.ToTable("PolygonAuthors", (string)null);
                });

            modelBuilder.Entity("Polygon.Entities.Rejudging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RejudgingId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Applied")
                        .HasColumnType("bit");

                    b.Property<int?>("ContestId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("IssuedBy")
                        .HasColumnType("int");

                    b.Property<int?>("OperatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.HasIndex("IssuedBy");

                    b.HasIndex("OperatedBy");

                    b.ToTable("PolygonRejudgings", (string)null);
                });

            modelBuilder.Entity("Polygon.Entities.Submission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SubmissionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CodeLength")
                        .HasColumnType("int");

                    b.Property<int>("ContestId")
                        .HasColumnType("int");

                    b.Property<int?>("ExpectedResult")
                        .HasColumnType("int");

                    b.Property<bool>("Ignored")
                        .HasColumnType("bit");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<int>("ProblemId")
                        .HasColumnType("int");

                    b.Property<int?>("RejudgingId")
                        .HasColumnType("int");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasMaxLength(262144)
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.HasIndex("Language");

                    b.HasIndex("ProblemId");

                    b.HasIndex("RejudgingId");

                    b.HasIndex("ContestId", "TeamId");

                    b.ToTable("PolygonSubmissions", (string)null);
                });

            modelBuilder.Entity("Polygon.Entities.SubmissionStatistics", b =>
                {
                    b.Property<int>("ContestId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("ProblemId")
                        .HasColumnType("int");

                    b.Property<int>("AcceptedSubmission")
                        .HasColumnType("int");

                    b.Property<int>("TotalSubmission")
                        .HasColumnType("int");

                    b.HasKey("ContestId", "TeamId", "ProblemId");

                    b.HasIndex("ContestId");

                    b.HasIndex("ProblemId");

                    b.HasIndex("ContestId", "ProblemId");

                    b.HasIndex("ContestId", "TeamId");

                    b.ToTable("PolygonStatistics", (string)null);
                });

            modelBuilder.Entity("Polygon.Entities.Testcase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TestcaseId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CustomInput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomOutput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<int>("InputLength")
                        .HasColumnType("int");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("bit");

                    b.Property<string>("Md5sumInput")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Md5sumOutput")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<int>("OutputLength")
                        .HasColumnType("int");

                    b.Property<int>("Point")
                        .HasColumnType("int");

                    b.Property<int>("ProblemId")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId");

                    b.HasIndex("ProblemId", "Rank")
                        .IsUnique();

                    b.ToTable("PolygonTestcases", (string)null);
                });

            modelBuilder.Entity("Polygon.Storages.SingleEntry", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("SatelliteSite.Entities.Auditlog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"), 1L, 1);

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<int?>("ContestId")
                        .HasColumnType("int");

                    b.Property<string>("DataId")
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.Property<int>("DataType")
                        .HasColumnType("int");

                    b.Property<string>("ExtraInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LogId");

                    b.HasIndex("DataType");

                    b.ToTable("Auditlogs", (string)null);
                });

            modelBuilder.Entity("SatelliteSite.Entities.Configuration", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayPriority")
                        .HasColumnType("int");

                    b.Property<bool>("Public")
                        .HasColumnType("bit");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Name");

                    b.ToTable("Configurations", (string)null);

                    b.HasData(
                        new
                        {
                            Name = "enable_register",
                            Category = "Identity",
                            Description = "Whether to allow user self registration.",
                            DisplayPriority = 0,
                            Public = true,
                            Type = "bool",
                            Value = "true"
                        },
                        new
                        {
                            Name = "oj_Codeforces_update_time",
                            Category = "Tenant",
                            Description = "Last update time of Codeforces.",
                            DisplayPriority = 0,
                            Public = false,
                            Type = "datetime",
                            Value = "null"
                        },
                        new
                        {
                            Name = "oj_Vjudge_update_time",
                            Category = "Tenant",
                            Description = "Last update time of Vjudge.",
                            DisplayPriority = 1,
                            Public = false,
                            Type = "datetime",
                            Value = "null"
                        },
                        new
                        {
                            Name = "oj_Hdoj_update_time",
                            Category = "Tenant",
                            Description = "Last update time of HDOJ.",
                            DisplayPriority = 2,
                            Public = false,
                            Type = "datetime",
                            Value = "null"
                        },
                        new
                        {
                            Name = "process_limit",
                            Category = "Judging",
                            Description = "Maximum number of processes that the submission is allowed to start (including shell and possibly interpreters).",
                            DisplayPriority = 1,
                            Public = true,
                            Type = "int",
                            Value = "64"
                        },
                        new
                        {
                            Name = "script_timelimit",
                            Category = "Judging",
                            Description = "Maximum seconds available for compile/compare scripts. This is a safeguard against malicious code and buggy scripts, so a reasonable but large amount should do.",
                            DisplayPriority = 2,
                            Public = true,
                            Type = "int",
                            Value = "30"
                        },
                        new
                        {
                            Name = "script_memory_limit",
                            Category = "Judging",
                            Description = "Maximum memory usage (in kB) by compile/compare scripts. This is a safeguard against malicious code and buggy script, so a reasonable but large amount should do.",
                            DisplayPriority = 3,
                            Public = true,
                            Type = "int",
                            Value = "2097152"
                        },
                        new
                        {
                            Name = "script_filesize_limit",
                            Category = "Judging",
                            Description = "Maximum filesize (in kB) compile/compare scripts may write. Submission will fail with compiler-error when trying to write more, so this should be greater than any *intermediate or final* result written by compilers.",
                            DisplayPriority = 4,
                            Public = true,
                            Type = "int",
                            Value = "540672"
                        },
                        new
                        {
                            Name = "timelimit_overshoot",
                            Category = "Judging",
                            Description = "Time that submissions are kept running beyond timelimit before being killed. Specify as \"Xs\" for X seconds, \"Y%\" as percentage, or a combination of both separated by one of \"+|&\" for the sum, maximum, or minimum of both.",
                            DisplayPriority = 5,
                            Public = true,
                            Type = "string",
                            Value = "\"1s|10%\""
                        },
                        new
                        {
                            Name = "output_storage_limit",
                            Category = "Judging",
                            Description = "Maximum size of error/system output stored in the database (in bytes); use \"-1\" to disable any limits.",
                            DisplayPriority = 6,
                            Public = true,
                            Type = "int",
                            Value = "60000"
                        },
                        new
                        {
                            Name = "diskspace_error",
                            Category = "Judging",
                            Description = "Minimum free disk space (in kB) on judgehosts.",
                            DisplayPriority = 7,
                            Public = true,
                            Type = "int",
                            Value = "1048576"
                        },
                        new
                        {
                            Name = "update_judging_seconds",
                            Category = "Judging",
                            Description = "Post updates to a judging every X seconds. Set to 0 to update after each judging_run.",
                            DisplayPriority = 8,
                            Public = true,
                            Type = "int",
                            Value = "0"
                        },
                        new
                        {
                            Name = "contest_last_rating_change_time",
                            Category = "Contest",
                            Description = "Last rating update time.",
                            DisplayPriority = 0,
                            Public = false,
                            Type = "datetime",
                            Value = "null"
                        });
                });

            modelBuilder.Entity("SatelliteSite.IdentityModule.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            ConcurrencyStamp = "9805fda4-f300-ff78-a6d8-faf0d8e418fd",
                            Description = "Administrative User",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR",
                            ShortName = "admin"
                        },
                        new
                        {
                            Id = -2,
                            ConcurrencyStamp = "f1722fb1-cd10-256b-48bb-71afd116ae66",
                            Description = "Blocked User",
                            Name = "Blocked",
                            NormalizedName = "BLOCKED",
                            ShortName = "blocked"
                        },
                        new
                        {
                            Id = -16,
                            ConcurrencyStamp = "c8259cc1-f159-cbf3-9348-ee1d3967d3ac",
                            Description = "Verified Student",
                            Name = "Student",
                            NormalizedName = "STUDENT",
                            ShortName = "student"
                        },
                        new
                        {
                            Id = -17,
                            ConcurrencyStamp = "89679840-61ae-1966-f3cc-56e0d6eb43a3",
                            Description = "Team Leader",
                            Name = "TeamLeader",
                            NormalizedName = "TEAMLEADER",
                            ShortName = "leader"
                        },
                        new
                        {
                            Id = -10,
                            ConcurrencyStamp = "44315c39-534d-ec0c-61f0-c0a5ed981cd9",
                            Description = "(Internal/System) Judgehost",
                            Name = "Judgehost",
                            NormalizedName = "JUDGEHOST",
                            ShortName = "judgehost"
                        },
                        new
                        {
                            Id = -11,
                            ConcurrencyStamp = "f25ae969-433c-3f4a-04ca-7ec12d2583cc",
                            Description = "Problem Provider",
                            Name = "ProblemCreator",
                            NormalizedName = "PROBLEMCREATOR",
                            ShortName = "prob"
                        },
                        new
                        {
                            Id = -30,
                            ConcurrencyStamp = "40100c40-6ca5-7bcb-48bc-41f2a939cbee",
                            Description = "CDS API user",
                            Name = "CDS",
                            NormalizedName = "CDS",
                            ShortName = "cds_api"
                        },
                        new
                        {
                            Id = -31,
                            ConcurrencyStamp = "8f8c37e1-a309-bd2d-6708-0519df89139b",
                            Description = "Contest Creator",
                            Name = "ContestCreator",
                            NormalizedName = "CONTESTCREATOR",
                            ShortName = "cont"
                        },
                        new
                        {
                            Id = -32,
                            ConcurrencyStamp = "d68c9040-7762-ab0b-06eb-19ce1b5a5120",
                            Description = "Temporary Team Account",
                            Name = "TemporaryTeamAccount",
                            NormalizedName = "TEMPORARYTEAMACCOUNT",
                            ShortName = "temp_team"
                        },
                        new
                        {
                            Id = -37,
                            ConcurrencyStamp = "76133040-8512-5021-491b-563056c3f919",
                            Description = "Plagiarism Detect User",
                            Name = "PlagUser",
                            NormalizedName = "PLAGUSER",
                            ShortName = "plaguser"
                        });
                });

            modelBuilder.Entity("SatelliteSite.NewsModule.Entities.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Content")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTimeOffset>("LastUpdate")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("Source")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Tree")
                        .HasColumnType("varbinary(max)");

                    b.HasKey("Id");

                    b.ToTable("News");
                });

            modelBuilder.Entity("SatelliteSite.OjUpdateModule.Entities.SolveRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Grade")
                        .HasColumnType("int");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Result")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("Category", "Grade");

                    b.ToTable("TenantSolveRecord", (string)null);
                });

            modelBuilder.Entity("SatelliteSite.XylabUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NickName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Plan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("RegisterTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("StudentVerified")
                        .HasColumnType("bit");

                    b.Property<bool>("SubscribeNews")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("StudentId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Tenant.Entities.Affiliation", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("EmailSuffix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation");

                    b.ToTable("TenantAffiliation", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Abbreviation = "null",
                            CountryCode = "CHN",
                            Name = "(none)"
                        });
                });

            modelBuilder.Entity("Tenant.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ContestId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.HasIndex("IsPublic");

                    b.HasIndex("SortOrder");

                    b.ToTable("TenantCategory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Color = "#ff2bea",
                            IsEligible = false,
                            IsPublic = false,
                            Name = "System",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = -2,
                            Color = "#33cc44",
                            IsEligible = false,
                            IsPublic = true,
                            Name = "Self-Registered",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = -3,
                            Color = "#ffffff",
                            IsEligible = true,
                            IsPublic = true,
                            Name = "Participants",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = -4,
                            Color = "#ffcc33",
                            IsEligible = false,
                            IsPublic = true,
                            Name = "Observers",
                            SortOrder = 0
                        },
                        new
                        {
                            Id = -5,
                            Color = "#ff99cc",
                            IsEligible = false,
                            IsPublic = true,
                            Name = "Organisation",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = -6,
                            Color = "#96d5ff",
                            IsEligible = false,
                            IsPublic = true,
                            Name = "Companies",
                            SortOrder = 1
                        });
                });

            modelBuilder.Entity("Tenant.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AffiliationId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("AffiliationId");

                    b.HasIndex("UserId");

                    b.ToTable("TenantTeachingClasses", (string)null);
                });

            modelBuilder.Entity("Tenant.Entities.ClassStudent", b =>
                {
                    b.Property<string>("StudentId")
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "ClassId");

                    b.HasIndex("ClassId");

                    b.ToTable("TenantClassStudents", (string)null);
                });

            modelBuilder.Entity("Tenant.Entities.GroupTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AffiliationId")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AffiliationId");

                    b.HasIndex("UserId");

                    b.ToTable("TenantTrainingTeams", (string)null);
                });

            modelBuilder.Entity("Tenant.Entities.GroupUser", b =>
                {
                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<bool?>("Accepted")
                        .HasColumnType("bit");

                    b.HasKey("TeamId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TenantTrainingUsers", (string)null);
                });

            modelBuilder.Entity("Tenant.Entities.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("AffiliationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("AffiliationId");

                    b.ToTable("TenantStudents", (string)null);
                });

            modelBuilder.Entity("Tenant.Entities.VerifyCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AffiliationId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("CreationTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<int>("RedeemCount")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AffiliationId");

                    b.HasIndex("Code");

                    b.HasIndex("UserId");

                    b.ToTable("TenantVerifyCodes", (string)null);
                });

            modelBuilder.Entity("Ccs.Entities.Balloon", b =>
                {
                    b.HasOne("Polygon.Entities.Submission", null)
                        .WithMany()
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ccs.Entities.Clarification", b =>
                {
                    b.HasOne("Ccs.Entities.Contest", null)
                        .WithMany()
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Polygon.Entities.Problem", null)
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ccs.Entities.Clarification", null)
                        .WithMany()
                        .HasForeignKey("ResponseToId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ccs.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("ContestId", "Recipient")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Ccs.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("ContestId", "Sender")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Ccs.Entities.ContestProblem", b =>
                {
                    b.HasOne("Ccs.Entities.Contest", null)
                        .WithMany()
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Polygon.Entities.Problem", null)
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Ccs.Entities.Event", b =>
                {
                    b.HasOne("Ccs.Entities.Contest", null)
                        .WithMany()
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ccs.Entities.Jury", b =>
                {
                    b.HasOne("Ccs.Entities.Contest", null)
                        .WithMany()
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SatelliteSite.XylabUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ccs.Entities.Member", b =>
                {
                    b.HasOne("SatelliteSite.XylabUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ccs.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("ContestId", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ccs.Entities.Printing", b =>
                {
                    b.HasOne("Ccs.Entities.Contest", null)
                        .WithMany()
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SatelliteSite.XylabUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ccs.Entities.RankCache", b =>
                {
                    b.HasOne("Ccs.Entities.Team", null)
                        .WithOne()
                        .HasForeignKey("Ccs.Entities.RankCache", "ContestId", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ccs.Entities.ScoreCache", b =>
                {
                    b.HasOne("Ccs.Entities.Team", null)
                        .WithMany()
                        .HasForeignKey("ContestId", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ccs.Entities.Team", b =>
                {
                    b.HasOne("Tenant.Entities.Affiliation", null)
                        .WithMany()
                        .HasForeignKey("AffiliationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Tenant.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Ccs.Entities.Contest", null)
                        .WithMany()
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ccs.Entities.Visibility", b =>
                {
                    b.HasOne("Tenant.Entities.Affiliation", null)
                        .WithMany()
                        .HasForeignKey("AffiliationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ccs.Entities.Contest", null)
                        .WithMany()
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("SatelliteSite.IdentityModule.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("SatelliteSite.XylabUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("SatelliteSite.XylabUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("SatelliteSite.IdentityModule.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SatelliteSite.XylabUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("SatelliteSite.XylabUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Polygon.Entities.Judging", b =>
                {
                    b.HasOne("Polygon.Entities.Judging", null)
                        .WithMany()
                        .HasForeignKey("PreviousJudgingId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Polygon.Entities.Rejudging", null)
                        .WithMany()
                        .HasForeignKey("RejudgingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Polygon.Entities.Judgehost", null)
                        .WithMany()
                        .HasForeignKey("Server")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Polygon.Entities.Submission", "s")
                        .WithMany("Judgings")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("s");
                });

            modelBuilder.Entity("Polygon.Entities.JudgingRun", b =>
                {
                    b.HasOne("Polygon.Entities.Judging", "j")
                        .WithMany()
                        .HasForeignKey("JudgingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Polygon.Entities.Testcase", null)
                        .WithMany()
                        .HasForeignKey("TestcaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("j");
                });

            modelBuilder.Entity("Polygon.Entities.Language", b =>
                {
                    b.HasOne("Polygon.Entities.Executable", null)
                        .WithMany()
                        .HasForeignKey("CompileScript")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Polygon.Entities.Problem", b =>
                {
                    b.HasOne("Polygon.Entities.Executable", null)
                        .WithMany()
                        .HasForeignKey("CompareScript")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Polygon.Entities.Executable", null)
                        .WithMany()
                        .HasForeignKey("RunScript")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Polygon.Entities.ProblemAuthor", b =>
                {
                    b.HasOne("Polygon.Entities.Problem", null)
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SatelliteSite.XylabUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Polygon.Entities.Rejudging", b =>
                {
                    b.HasOne("Ccs.Entities.Contest", null)
                        .WithMany()
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SatelliteSite.XylabUser", null)
                        .WithMany()
                        .HasForeignKey("IssuedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SatelliteSite.XylabUser", null)
                        .WithMany()
                        .HasForeignKey("OperatedBy")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Polygon.Entities.Submission", b =>
                {
                    b.HasOne("Polygon.Entities.Language", "l")
                        .WithMany()
                        .HasForeignKey("Language")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Polygon.Entities.Problem", "p")
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Polygon.Entities.Rejudging", null)
                        .WithMany()
                        .HasForeignKey("RejudgingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("l");

                    b.Navigation("p");
                });

            modelBuilder.Entity("Polygon.Entities.SubmissionStatistics", b =>
                {
                    b.HasOne("Polygon.Entities.Problem", null)
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Polygon.Entities.Testcase", b =>
                {
                    b.HasOne("Polygon.Entities.Problem", null)
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SatelliteSite.XylabUser", b =>
                {
                    b.HasOne("Tenant.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Tenant.Entities.Category", b =>
                {
                    b.HasOne("Ccs.Entities.Contest", null)
                        .WithMany()
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Tenant.Entities.Class", b =>
                {
                    b.HasOne("Tenant.Entities.Affiliation", "Affiliation")
                        .WithMany()
                        .HasForeignKey("AffiliationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SatelliteSite.XylabUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Affiliation");
                });

            modelBuilder.Entity("Tenant.Entities.ClassStudent", b =>
                {
                    b.HasOne("Tenant.Entities.Class", null)
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tenant.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tenant.Entities.GroupTeam", b =>
                {
                    b.HasOne("Tenant.Entities.Affiliation", "Affiliation")
                        .WithMany()
                        .HasForeignKey("AffiliationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SatelliteSite.XylabUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Affiliation");
                });

            modelBuilder.Entity("Tenant.Entities.GroupUser", b =>
                {
                    b.HasOne("Tenant.Entities.GroupTeam", null)
                        .WithMany("Users")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SatelliteSite.XylabUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tenant.Entities.Student", b =>
                {
                    b.HasOne("Tenant.Entities.Affiliation", null)
                        .WithMany()
                        .HasForeignKey("AffiliationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Tenant.Entities.VerifyCode", b =>
                {
                    b.HasOne("Tenant.Entities.Affiliation", null)
                        .WithMany()
                        .HasForeignKey("AffiliationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SatelliteSite.XylabUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Polygon.Entities.Submission", b =>
                {
                    b.Navigation("Judgings");
                });

            modelBuilder.Entity("Tenant.Entities.Class", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Tenant.Entities.GroupTeam", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
